// Plain-language card for one outcome. Mounts when its row is expanded, fetches the
// cached explanation (generated once by Gemini on the backend), and shows it.

import { useCallback, useEffect, useState } from "react";
import { Explanation, fetchExplanation } from "../api";

type State =
  | { status: "loading" }
  | { status: "error"; message: string }
  | { status: "ready"; data: Explanation };

export function ExplanationPanel({ marketId }: { marketId: string }) {
  const [state, setState] = useState<State>({ status: "loading" });

  const load = useCallback(async () => {
    setState({ status: "loading" });
    try {
      setState({ status: "ready", data: await fetchExplanation(marketId) });
    } catch (e) {
      setState({ status: "error", message: (e as Error).message });
    }
  }, [marketId]);

  useEffect(() => {
    load();
  }, [load]);

  return (
    <div>
      <p className="mb-2 text-micro uppercase text-ink-400">Explanation</p>

      {state.status === "loading" && <CardSkeleton />}

      {state.status === "error" && (
        <div className="text-sm text-ink-600">
          <p>Couldn't generate an explanation. {state.message}</p>
          <button
            onClick={load}
            className="mt-3 rounded-md border border-line-strong px-3 py-1.5 text-sm font-medium text-ink-900 transition-colors hover:bg-surface"
          >
            Try again
          </button>
        </div>
      )}

      {state.status === "ready" && <Card data={state.data} />}
    </div>
  );
}

function Card({ data }: { data: Explanation }) {
  return (
    <div className="space-y-4">
      <p className="text-base text-ink-900">{data.summary}</p>

      {data.description_thin && (
        <p className="rounded-md bg-surface px-3 py-2 text-caption text-ink-600">
          The official resolution text is thin, so some details below are limited to
          what it actually states.
        </p>
      )}

      <div className="grid gap-3 sm:grid-cols-2">
        <Field label="If “Yes”">{data.yes_meaning}</Field>
        <Field label="If “No”">{data.no_meaning}</Field>
      </div>

      <Field label="What makes “Yes” resolve true">{data.yes_resolves}</Field>

      <p className="text-micro text-ink-400">
        Generated by {data.model} from the market's official description.
      </p>
    </div>
  );
}

function Field({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div>
      <p className="mb-1 text-micro uppercase text-ink-400">{label}</p>
      <p className="text-sm text-ink-900">{children}</p>
    </div>
  );
}

function CardSkeleton() {
  return (
    <div className="animate-pulse space-y-3">
      <div className="h-4 w-11/12 rounded bg-line" />
      <div className="h-4 w-3/4 rounded bg-line" />
      <div className="mt-4 grid gap-3 sm:grid-cols-2">
        <div className="h-12 rounded bg-line" />
        <div className="h-12 rounded bg-line" />
      </div>
    </div>
  );
}
